import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  console.log(inter)
  return (
    <html lang="en">
      <body>
        <main className='flex flex-1 flex-col'>
          <div className='flex justify-center items-center h-20 border-b border-black border-solid'>
            header
          </div>
          <div className="mainControlArea flex-1">
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
